In [4]:
import pandas as pd

In [5]:
df = pd.read_excel("/content/base_original_pmdf.xlsx")

In [3]:
df.head(5)

,Unnamed: 0,ANO: 2024,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,INCIDENCIA: LEI 11.340 - MARIA DA PENHA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NUMERO,DATA HORA,INCIDENCIA,CIDADE,BAIRRO,QUADRA,COMPLEMENTO,HISTORICO,LATITUDE,LONGITUDE
3,NaN,2024010100698028682,2024-01-01 00:05:00,LEI 11.340 (MARIA DA PENHA),NUCLEO BANDEIRANTE,SEM_SETOR,2ª AVENIDA,APARTAMENTO 102,Foi passado uma situação de monitorado por tor...,"-15,86942","-47,96948"
4,NaN,2024010100691028683,2024-01-01 01:07:00,LEI 11.340 (MARIA DA PENHA),SAO SEBASTIAO,BAIRRO CENTRO,RUA 64A,CASA 31,Acionado para atendimento de ocorrência de cri...,"-15,94647","-48,06821"

In [6]:
df.columns = df.iloc[2]
df = df.iloc[3:].reset_index(drop=True)
df = df.iloc[:, 1:]

In [7]:
df.head(35)

2,NUMERO,DATA HORA,INCIDENCIA,CIDADE,BAIRRO,QUADRA,COMPLEMENTO,HISTORICO,LATITUDE,LONGITUDE
0,2024010100698028682,2024-01-01 00:05:00,LEI 11.340 (MARIA DA PENHA),NUCLEO BANDEIRANTE,SEM_SETOR,2ª AVENIDA,APARTAMENTO 102,Foi passado uma situação de monitorado por tor...,"-15,86942","-47,96948"
1,2024010100691028683,2024-01-01 01:07:00,LEI 11.340 (MARIA DA PENHA),SAO SEBASTIAO,BAIRRO CENTRO,RUA 64A,CASA 31,Acionado para atendimento de ocorrência de cri...,"-15,94647","-48,06821"
2,2024010100024028697,2024-01-01 00:58:00,LEI 11.340 (MARIA DA PENHA),SAMAMBAIA,SEM_SETOR,QR 403,CASA 20,"No dia 01 de janeiro de 2024, às 00:58, a viat...","-15,87031","-48,09789"
3,2024010100005028734,2024-01-01 02:53:00,LEI 11.340 (MARIA DA PENHA),TAGUATINGA,SETOR D SUL,QSD 33,LOTE 04 APTO 202,"Não há apto no lote 04, ou seja, endereço inco...","-15,94647","-48,06821"
4,2024010100691028741,2024-01-01 02:08:00,LEI 11.340 (MARIA DA PENHA),SAO SEBASTIAO,SEM_SETOR,NaN,VILA DO BOA,Acionado para atendimento de ocorrência com in...,"-15,94647","-48,06821"
5,2024010100005028747,2024-01-01 02:04:00,LEI 11.340 (MARIA DA PENHA),TAGUATINGA,SETOR F SUL,QSF 2,CASA 303,A Sra Daniela visivelmente aparentava ter prob...,"-15,94647","-48,06821"
6,2024010100005028748,2024-01-01 02:53:00,LEI 11.340 (MARIA DA PENHA),TAGUATINGA,SETOR E SUL,QSE 22,FAVELA AO LADO DA LINHA DO METRÔ,A equipe fez abordagem a dois homens suspeitos...,"-15,94647","-48,06821"
7,2024010100700028750,2024-01-01 01:57:00,LEI 11.340 (MARIA DA PENHA),RECANTO DAS EMAS,SEM_SETOR,QUADRA 511,CASA 23,"Quando em patrulhamento pelo Recanto das Emas,...","-15,93132","-48,10732"
8,2024010100691028788,2024-01-01 01:34:00,LEI 11.340 (MARIA DA PENHA),SAO SEBASTIAO,BAIRRO TRADICIONAL,NaN,"RUA 21, 41",Fomos acionados via COPOM para averiguar situa...,"-15,94647","-48,06821"
9,2024010100034028800,2024-01-01 08:40:00,LEI 11.340 (MARIA DA PENHA),PLANALTINA,SH ARAPOANGA_CONDOMINIO ARAPOANGA,QUADRA 15/17M,CASA 86 A,Quando em patrulhamento este prefixo foi acion...,"-15,6448","-47,63412"
10,2024010100691028802,2024-01-01 04:01:00,LEI 11.340 (MARIA DA PENHA),SAO SEBASTIAO,SEM_SETOR,NaN,CAPÃO COMPRIDO,"Após acionamento via copom, o prefixo 3748 se ...","-15,94647","-48,06821"
11,2024010100012028810,2024-01-01 07:00:00,LEI 11.340 (MARIA DA PENHA),GUARA,GUARÁ II - POLO DE MODA,RUA 21,"LOTE 26, AP 401",A RP 3971 ao assumir o serviço ordinário foi i...,"-15,94647","-48,06821"
12,2024010100691028812,2024-01-01 08:10:00,LEI 11.340 (MARIA DA PENHA),SAO SEBASTIAO,BAIRRO VILA NOVA,NaN,RUA 14 CASA 661,A equipe da 4427 fora acionada por AD41 para a...,"-15,94647","-48,06821"
13,2024010100684028821,2024-01-01 07:00:00,LEI 11.340 (MARIA DA PENHA),AGUAS CLARAS,SH ARNIQUEIRAS_COLONIA AGRICOLA ARNIQUEIRA,NaN,SHA CHÁCARA 82 CONJUNTO 03 LOTE 07,O prefixo foi acionado via COPOM para averigua...,"-15,94647","-48,06821"
14,2024010100699028826,2024-01-01 07:41:00,LEI 11.340 (MARIA DA PENHA),SANTA MARIA,SEM SETOR,QR 418,CASA 03,Equipe policial acionada via centro de comunic...,"-16,01268","-47,98707"
15,2024010100012028828,2024-01-01 10:54:00,LEI 11.340 (MARIA DA PENHA),GUARA,GUARÁ II,QE 40,EDIFÍCIO EMIVAL LUÍS AP 124,A RP 3971 em patrulhamento na área do Guará II...,"-15,94647","-48,06821"
16,2024010100708028834,2024-01-01 01:20:00,LEI 11.340 (MARIA DA PENHA),RIACHO FUNDO II,RIACHO FUNDO II 1A ETAPA,QN 8A,LOTE 01,Quando em patrulhamento na área do Riacho Fund...,"-15,90464","-48,04431"
17,2024010100034028843,2024-01-01 12:11:00,LEI 11.340 (MARIA DA PENHA),PLANALTINA,SH ARAPOANGA_CONDOMINIO ARAPOANGA,QUADRA 2K,CASA 09 C,Quando em patrulhamento este prefixo foi acion...,"-15,64017","-47,63308"
18,2024010100690028844,2024-01-01 12:05:00,LEI 11.340 (MARIA DA PENHA),ITAPOA,SH ITAPOA_CONDOMINIO DEL LAGO II,QR 371,CASA 07,"A Polícia Militar do Distrito Federal, por mei...","-15,94647","-48,06821"
19,2024010100034028853,2024-01-01 13:09:00,LEI 11.340 (MARIA DA PENHA),PLANALTINA,SH MESTRE D_ARMAS_CONDOMINIO VIVENDAS NOVA PET...,NaN,ASSENTAMENTO MIGUEL LOBATO CJ 02 CASA 42,"Quando em patrulhamento na estância, fomos aci...","-15,94647","-48,06821"
20,2024010100691028863,2024-01-01 13:00:00,LEI 11.340 (MARIA DA PENHA),SAO SEBASTIAO,SEM_SETOR,NaN,CHÁCARA 4 ZUMBI DOS PALMARES,Solicitante informou que havia sido espancad...,"-15,94647","-48,06821"
21,2024010100691028869,2024-01-01 14:10:00,LEI 11.340 (MARIA DA PENHA),SAO SEBASTIAO,NÚCLEO RURAL MORRO DA CRUZ,NaN,RUA 6 CASA 02 RESIDENCIAL VITÓRIA,Solicitante informou que foi espancada pelo m...,"-15,94647","-48,06821"
22,2024010100024028871,2024-01-01 00:30:00,LEI 11.340 (MARIA DA PENHA),SAMAMBAIA,SEM_SETOR,QR 104,CASA 02,"Nesta data, por volta de 00:30 guarnição foi a...","-15,87393","-48,08299"
23,2024010100684028873,2024-01-01 12:31:00,LEI 11.340 (MARIA DA PENHA),VICENTE PIRES,SEM_SETOR,NaN,RUA 04 CHAC 01 LOTE 08 APTO 204 ED BRENO LUIZ,"No dia 01/01/2024, durante o serviço voluntári...","-15,94647","-48,06821"
24,2024010100024028877,2024-01-01 03:00:00,LEI 11.340 (MARIA DA PENHA),SAMAMBAIA,SEM_SETOR,QR 615,CASA 09,A vítima informou que seu ex companheiro estav...,"-15,87416","-48,11624"
25,2024010100024028880,2024-01-01 04:55:00,LEI 11.340 (MARIA DA PENHA),SAMAMBAIA,SEM_SETOR,QR 508,CASA 33,A vitima não quis representar . Ocorrência res...,"-15,88199","-48,07464"
26,2024010100699028898,2024-01-01 07:35:00,LEI 11.340 (MARIA DA PENHA),SANTA MARIA,SEM SETOR,QR 210,CASA 08,Prefixo foi acionado para ocorrência onde uma ...,"-16,0198","-48,01939"
27,2024010100023028900,2024-01-01 14:20:00,LEI 11.340 (MARIA DA PENHA),CEILANDIA,SETOR M,QNM 25,CASA 38,"A equipe compareceu no local, foram utilizados...","-15,83588","-48,09365"
28,2024010100023028905,2024-01-01 15:30:00,LEI 11.340 (MARIA DA PENHA),CEILANDIA,SETOR N,QNN 5,CASA 25,A equipe entrou em contato com a senhora Lília...,"-15,80869","-48,11528"
29,2024010100023028919,2024-01-01 16:50:00,LEI 11.340 (MARIA DA PENHA),CEILANDIA,SETOR N,QNN 9,CASA 43,A equipe compareceu no local e entrou em conta...,"-15,80238","-48,12212"
30,2024010100690028920,2024-01-01 14:30:00,LEI 11.340 (MARIA DA PENHA),ITAPOA,SH ITAPOA_CONDOMINIO DEL LAGO II,QR 318,CONJUNTO M CASA 82,Este prefixo 3518 foi acionado via AD40 para v...,"-15,94647","-48,06821"
31,2024010100690028929,2024-01-01 14:00:00,LEI 11.340 (MARIA DA PENHA),PARANOA,PARANOA PARQUE,SEM QUADRA,NaN,"A PMDF por meio deste prefixo, foi acionada vi...","-15,76589","-47,79357"
32,2024010100025029033,2024-01-01 19:52:00,LEI 11.340 (MARIA DA PENHA),GAMA,DF-483,NaN,PERTO DO PRESÍDIO - CAIC,"Por determinação de AD29, que recebeu solicita...","-15,94647","-48,06821"
33,2024010100025029036,2024-01-01 20:48:00,LEI 11.340 (MARIA DA PENHA),GAMA,SETOR LESTE,QUADRA 28,CASA 26 ESQUINA,"Por determinação do COPOM, este prefixo compar...","-15,94647","-48,06821"
34,2024010100699029042,2024-01-01 20:32:00,LEI 11.340 (MARIA DA PENHA),SANTA MARIA,SH RIBEIRAO_CONDOMINIO PORTO RICO,NaN,1 ETAPA CONJUNTO J CASA 31,"Quando em patrulhamento, esta equipe policial ...","-15,94647","-48,06821"

In [8]:
import re

PALAVRAS_COMUNS = {
    "A", "AO", "AOS", "AS", "ATÉ", "ATE", "COM", "COMO", "DA", "DAS", "DE",
    "DO", "DOS", "E", "EM", "FOI", "PARA", "POR", "QUE", "SE", "SUA", "SUAS",
    "SEU", "SEUS", "UM", "UMA", "UNS", "UMAS", "NA", "NAS", "NO", "NOS",
    "NÃO", "NAO", "MAS", "OU", "ELE", "ELA", "ELES", "ELAS", "EU", "NÓS",
    "NOS", "ISSO", "ESTE", "ESTA", "ESSE", "ESSA", "AQUELE", "AQUELA",
    "VITIMA", "VÍTIMA", "AUTOR", "AUTORA", "EQUIPE", "LOCAL", "GUARNIÇÃO",
    "GUARNICAO", "HOSPITAL", "DELEGACIA", "POLICIA", "POLÍCIA", "AGRESSOR",
    "AGRESSÃO", "AGRESSAO", "OCORRÊNCIA", "OCORRENCIA", "PREFIXO", "AREA",
    "ÁREA", "APOIO", "CASA", "RUA", "ROSTO", "CABEÇA", "CABECA", "LADO",
    "MOMENTO", "OBJETIVO", "AÇÃO", "ACAO", "CHEGADA", "FATOS", "FATO",
    "FILHA", "FILHO", "FILHOS", "FILHAS", "PAI", "MÃE", "MAE", "PAIS",
    "NETOS", "AVÔ", "AVO", "VIZINHOS", "VIZINHO", "CRIANÇAS", "CRIANCAS",
    "CRIANÇA", "CRIANCA", "SOCORRO", "OBJETO", "TIJOLO", "ESTACA", "MURRO",
    "GOLPE", "IMPACTO", "CORTE", "SANGUE", "CHOQUE", "NERVOSA", "NERVOSO",
    "PRIMEIRO", "PRIMEIROS", "ATENDIMENTO", "MEDICO", "MÉDICO", "SOCORROS",
    "POSTERIORMENTE", "ANTERIORMENTE", "IMEDIATO", "IMEDIATA", "INSTANTES",
    "APOS", "APÓS", "ANTES", "DURANTE", "ENQUANTO", "SEGUIDA", "CONTINUO",
    "CONTÍNUO", "IMPORTANTE", "DESTACAR", "TENTATIVA", "TENTOU", "LOGROU",
    "EXITO", "ÊXITO", "SUCESSO", "PROVIDÊNCIAS", "PROVIDENCIAS", "MEDIDAS",
    "PROTETIVAS", "JUDICIARIO", "JUDICIÁRIO", "POLICIAL", "POLICIAIS",
    "PODER", "CURATELA", "CUIDADO", "RESPONSABILIZOU", "ZELO", "REGISTRO",
    "REGISTROU", "APURAÇÃO", "APURACAO", "LOCALIZADO", "LOCALIZAÇÃO",
    "LOCALIZACAO", "IDENTIFICAR", "QUALIFICAÇÃO", "QUALIFICACAO", "FOTO",
    "PATRULHAMENTO", "DILIGENCIAS", "DILIGÊNCIAS", "PROXIMIDADES",
    "INFRAESTRUTURA", "URBANISTICA", "PRECÁRIA", "PRECARIA", "BARRACOS",
    "CONJUNTO", "QUADRA", "CHACARA", "ENDEREÇO", "ENDERECO", "INFORMADO",
    "INFORMOU", "INFORMARAM", "NARRADOS", "IMINENTE", "PERIGO", "CIÊNCIA",
    "CIENCIA", "DESLOCOU", "DESLOCARAM", "ENCAMINHADA", "ENCAMINHOU",
    "ENCONTROU", "ENCONTRAR", "CONSTATAR", "CONSTATADO", "CONSEGUINDO",
    "RETORNAR", "MATAR", "EVADIU", "IMPEDIRAM", "INTERVIRAM", "GRITANDO",
    "SAIU", "PEGOU", "USOU", "CAIU", "DISCUTIU", "DESFERIU", "REALIZOU",
    "REPASSOU", "REQUEREU", "ENTREGOU", "COMPARECERAM", "SOLICITOU",
    "ACIONADA", "ACIONADOS", "AVERIGUAR", "POSSIVEL", "POSSÍVEL",
    "SITUAÇÃO", "SITUACAO", "VIOLÊNCIA", "VIOLENCIA", "DOMÉSTICA",
    "DOMESTICA", "AMEAÇA", "AMEACA", "CÁRCERE", "CARCERE", "PRIVADO",
    "PROFUNDO", "PROFUNDA", "PROLONGAVA", "PROVENIENTE", "APROXIMADAMENTE",
    "METADE", "QUANTIDADE", "GRANDE", "ESQUERDO", "DIREITO", "TESTA",
    "INCERTO", "CRIMINOSA", "PROSSEGUIMENTO", "EXTREMIDADE", "PONTIAGUDA",
    "ALCANCE", "APARENTAVA", "CEIFAR", "AGRESSÕES", "AGRESSOES", "ACERTAR",
    "TOMANDO", "RUMO", "PROMESSA", "CHAMADOS", "CBMDF", "COPOM", "CBM",
    "SGT", "SRA", "SR", "GAE", "AD", "UR", "GTOP", "PCDF", "FLAGRANTE",
    "AGENTE", "MULHER", "HOMEM", "PALAVRA", "CALAO", "CALHÃO", "CHUTE",
    "CIUMES", "CIÚMES", "PARTES", "PROVIDENCIAS", "CABIVEIS", "ESPOSA",
    "MARIDO", "SOGRA", "SOGRO", "GENRO", "NORA", "CUNHADA", "CUNHADO",
    "CONCUNHADA", "CONCUNHADO", "CRIANÇA", "CASAL", "CONDUZIDO", "PRESO",
    "ALGEMAS", "EMBRIAGUEZ", "EMBRIAGADO", "ALCOOL", "ÁLCOOL", "ARMA",
    "FOGO", "BUSCA", "DOMICILIAR", "PRISÃO", "PRISAO", "PROCEDIMENTO",
    "LAVRATURA", "DELEGACIA", "OCORRENCIA", "OCORRÊNCIA",
}

NOMES_BRASILEIROS = [
    # Femininos
    "Ana", "Maria", "Fernanda", "Juliana", "Amanda", "Camila", "Beatriz",
    "Larissa", "Leticia", "Letícia", "Patricia", "Patrícia", "Gabriela",
    "Rafaela", "Renata", "Vanessa", "Claudia", "Cláudia", "Sandra", "Simone",
    "Mariana", "Adriana", "Cristiane", "Cristina", "Luciana", "Rosana",
    "Rosangela", "Rosângela", "Fatima", "Fátima", "Regina", "Vera", "Lucia",
    "Lúcia", "Eliane", "Elisangela", "Elisângela", "Aparecida", "Aline",
    "Bianca", "Bruna", "Carolina", "Carla", "Daniela", "Deborah", "Debora",
    "Débora", "Edilene", "Edna", "Elza", "Erica", "Érica", "Flavia", "Flávia",
    "Gisele", "Giselle", "Giovana", "Gilvania", "Gilvânia", "Iara", "Ingrid",
    "Isabela", "Isabella", "Jessica", "Jéssica", "Josefa", "Joyce", "Julia",
    "Júlia", "Juliane", "Karina", "Katia", "Kátia", "Keyna", "Laura", "Leia",
    "Leidiana", "Leidiane", "Lilian", "Liliane", "Livia", "Lívia", "Lorena",
    "Luana", "Luiza", "Luíza", "Marta", "Melissa", "Michele", "Michelle",
    "Monica", "Mônica", "Naiara", "Natalia", "Natália", "Nathalia", "Nathália",
    "Nilma", "Paloma", "Paula", "Priscila", "Raquel", "Rebeca", "Rebecca",
    "Rita", "Roberta", "Rosa", "Sabrina", "Sara", "Sarah", "Silvia", "Sílvia",
    "Solange", "Sonia", "Sônia", "Sueli", "Suely", "Suzana", "Suzane",
    "Tais", "Taís", "Tatiana", "Tatiane", "Telma", "Tereza", "Teresa",
    "Thais", "Thaís", "Thalia", "Thália", "Valdirene", "Valeria", "Valéria",
    "Viviane", "Viviani", "Wanda", "Yasmin", "Yara", "Manoela", "Manuela",
    "Kelma", "Gleice", "Gleicy", "Jaqueline", "Jacqueline", "Elaine",
    "Valentina", "Helena", "Alice", "Elisa", "Clarice", "Aurora", "Maite",
    "Maitê", "Catarina", "Heloisa", "Heloísa", "Taina", "Tainá", "Sofia",
    "Daiane", "Monique", "Nicole", "Barbara", "Bárbara", "Keitiany",
    "Ludimila", "Karolayne", "Jarinete", "Andressa", "Rosemery", "Ariane",
    "Francisca", "Benedita", "Sebastiana", "Antonia", "Antônia", "Carmelita",
    "Inacia", "Inácia", "Dalva", "Nilza", "Vania", "Vânia", "Noemia",
    "Noêmia", "Odete", "Zilda", "Efigenia", "Efigênia", "Jandira", "Marlene",
    "Ivone", "Dirce", "Celia", "Célia", "Nair", "Neide", "Zuleide", "Zulmira",
    "Raimunda", "Quiteria", "Quitéria", "Gertrudes", "Edeltrudes", "Doralice",
    "Janete", "Arlete", "Jucimara", "Rosilene", "Cidalia", "Cidália",
    "Magnolia", "Magnólia", "Zoraide", "Iracema", "Lindalva", "Jucelia",
    "Jucélia", "Valdenia", "Valdênia", "Josenilda", "Rosicleide", "Claudete",
    "Marilene", "Jucilene", "Cleonice", "Dejanira", "Terezinha", "Luzinete",
    "Ivonete", "Valquiria", "Valquíria", "Nadia", "Nádia",
    # Masculinos
    "Adam", "Adilson", "Adriano", "Alexandre", "Alex", "Anderson", "Andre",
    "André", "Antonio", "Antônio", "Bruno", "Carlos", "Caio", "Claudio",
    "Cláudio", "Daniel", "Danilo", "David", "Diego", "Douglas", "Eduardo",
    "Edson", "Elias", "Emanuel", "Emerson", "Evandro", "Fabio", "Fábio",
    "Felipe", "Filipe", "Fernando", "Francisco", "Frederico", "Gabriel",
    "Giordano", "Gilberto", "Guilherme", "Gustavo", "Henrique", "Hugo",
    "Igor", "Ivan", "Iron", "Izaque", "Jefferson", "Jonathan", "Jorge",
    "Jose", "José", "Joao", "João", "Julio", "Júlio", "Junior", "Júnior",
    "Kaique", "Kaio", "Leonardo", "Leandro", "Lucas", "Luciano", "Luis",
    "Luís", "Luiz", "Marcelo", "Marcio", "Márcio", "Marcos", "Mateus",
    "Matheus", "Mauricio", "Maurício", "Miguel", "Murilo", "Nelson",
    "Nicolas", "Nicolau", "Paulo", "Pedro", "Rafael", "Raphael", "Ricardo",
    "Roberto", "Rodrigo", "Romulo", "Rômulo", "Rogerio", "Rogério", "Ruan",
    "Samuel", "Sergio", "Sérgio", "Silas", "Tiago", "Thiago", "Vagner",
    "Valter", "Victor", "Vinicius", "Vinícius", "Wagner", "Wallace",
    "Wallyson", "Wander", "Washington", "Wellington", "Wellinton", "Welder",
    "William", "Willian", "Kelmon", "Kelvin", "Kevin", "Renato", "Otavio",
    "Otávio", "Davi", "Enzo", "Theo", "Arthur", "Benjamin", "Noah",
    "Heitor", "Lorenzo", "Raul", "Tadeu", "Bento", "Cicero", "Cícero",
    "Baltazar", "Ezequiel", "Ismael", "Adalberto", "Osvaldo", "Severino",
    "Raimundo", "Valdemar", "Hermenegildo", "Aristides", "Leonidas",
    "Leônidas", "Eustaquio", "Eustáquio", "Genesio", "Genésio", "Onofre",
    "Epifanio", "Epifânio", "Deolindo", "Juvenal", "Agenor", "Moacir",
    "Ubirajara", "Jurandir", "Valdir", "Vanderlei", "Ademir", "Valmir",
    "Olegario", "Olegário", "Wenceslau", "Alcides", "Florisvaldo",
    "Gervasio", "Gervásio", "Lindomar", "Aureliano", "Bernardino",
    "Claudionor", "Djalma", "Edivaldo", "Josue", "Josué", "Josias",
    "Salomao", "Salomão", "Tobias", "Zacarias", "Emanoel", "Abdias",
    "Jeferson", "Edmilson", "Amarildo", "Josenildo", "Roberval", "Gleidson",
    "Uelinton", "Halrisson", "Atylla", "Reginaldo", "Zilli", "Souto",
    # Sobrenomes comuns
    "Silva", "Santos", "Oliveira", "Souza", "Sousa", "Rodrigues", "Alves",
    "Ferreira", "Pereira", "Lima", "Gomes", "Costa", "Ribeiro", "Martins",
    "Carvalho", "Almeida", "Lopes", "Rocha", "Nascimento", "Moreira",
    "Nunes", "Barbosa", "Cavalcanti", "Dias", "Cardoso", "Moura", "Ramos",
    "Campos", "Pinto", "Freitas", "Teixeira", "Monteiro", "Vieira",
    "Fonseca", "Azevedo", "Mendes", "Cunha", "Pinheiro", "Medeiros",
    "Batista", "Araujo", "Araújo", "Cruz", "Melo", "Brito", "Xavier",
    "Simoes", "Simões", "Iacozzilli", "Caseiro", "Giordano",
]

_vistos = set()
_NOMES_UNICOS = []
for n in NOMES_BRASILEIROS:
    if n.lower() not in _vistos:
        _vistos.add(n.lower())
        _NOMES_UNICOS.append(n)

_NOMES_COMPILED = [
    re.compile(r'\b' + re.escape(n) + r'\b', re.IGNORECASE)
    for n in _NOMES_UNICOS
]

WHITELIST = [
    r'Lei\s+Maria\s+da\s+Penha', r'Maria\s+da\s+Penha',
    r'Código\s+Penal', r'Ministério\s+Público',
    r'Boletim\s+de\s+Ocorrência', r'Polícia\s+Civil', r'Polícia\s+Militar',
    r'Corpo\s+de\s+Bombeiros', r'Defensoria\s+Pública', r'Vara\s+Criminal',
    r'Hospital\s+Regional', r'COPOM', r'CBM/DF', r'CBM', r'CBMDF',
    r'Plano\s+Piloto', r'Asa\s+Sul', r'Asa\s+Norte',
    r'Brasília', r'Gama', r'Taguatinga', r'Brazlândia',
    r'Sobradinho\s+II', r'Sobradinho', r'Planaltina', r'Paranoá',
    r'Núcleo\s+Bandeirante', r'Ceilândia', r'Guará', r'Cruzeiro',
    r'Samambaia\s+Norte', r'Samambaia\s+Sul', r'Samambaia',
    r'Santa\s+Maria', r'São\s+Sebastião', r'Recanto\s+das\s+Emas',
    r'Lago\s+Sul', r'Riacho\s+Fundo\s+II', r'Riacho\s+Fundo',
    r'Lago\s+Norte', r'Candangolândia', r'Águas\s+Claras',
    r'Sudoeste', r'Octogonal', r'Varjão', r'Park\s+Way',
    r'Estrutural', r'Jardim\s+Botânico', r'Itapoã',
    r'Vicente\s+Pires', r'Fercal', r'Noroeste', r'Distrito\s+Federal',
    r'Delegacia\s+de\s+Pol[íi]cia',
    r'1[ºª]\s+Delegacia', r'26[ºª]\s+Delegacia', r'30[ºª]\s+Delegacia',
]

_WHITELIST_COMPILED = [
    (re.compile(p, re.IGNORECASE), f"__WL{i}__")
    for i, p in enumerate(WHITELIST)
]

CONTEXTO = re.compile(
    r'\b(solicitante|v[íi]tima|autor[a]?|acusad[oa]|suspeito[a]?|'
    r'testemunha|comunicante|requerente|agente|policial|padrasto|madrasta|'
    r'companheiro|companheira|namorado[a]?|irm[ãa]o?|filh[oa]|'
    r'esposo|esposa|marido|sogr[ao]|genro|nora|cunhad[ao]|concunhad[ao]|'
    r'm[ãa]e\s+d[ao]|pai\s+d[ao]|'
    r'posteriormente\s+identificad[oa]\s+como(?:\s+sendo)?|'
    r'identificad[oa]\s+como(?:\s+sendo)?|'
    r'pel[oa]\s+agente|'
    r'senhora|senhor|srta\.?|sra\.?|sr\.?|sr[aª]\.?|sr[oº]\.?|sgt\.?|cb\.?|sd\.?|'
    r'exma?\.?\s*sra?\.?|dr\.?|dra\.?|'
    r'com\s+[oa]|juntamente\s+com|contato\s+com)'
    r'[\s,\(]+'
    r'([A-ZÁÉÍÓÚÂÊÔÃÕÀÜÇ][A-ZÁÉÍÓÚÂÊÔÃÕÀÜÇa-záéíóúâêôãõàüç]+'
    r'(?:\s+(?:da?|de|do|dos|das)\s+[A-ZÁÉÍÓÚÂÊÔÃÕÀÜÇ][a-záéíóúâêôãõàüç]+|'
    r'\s+[A-ZÁÉÍÓÚÂÊÔÃÕÀÜÇ][A-ZÁÉÍÓÚÂÊÔÃÕÀÜÇa-záéíóúâêôãõàüç]+)*)',
    re.IGNORECASE
)

_CPF      = re.compile(r'\b\d{3}[\.\s]?\d{3}[\.\s]?\d{3}[\-\s]?\d{2}\b')
_CNPJ     = re.compile(r'\b\d{2}[\.\s]?\d{3}[\.\s]?\d{3}[\/\.]?\d{4}[\-]?\d{2}\b')
_EMAIL    = re.compile(r'[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}')
_TELEFONE = re.compile(r'\(?\d{2}\)?\s?\d{4,5}[\-\s]?\d{4}')
_CODIGO   = re.compile(r'\b\d{5,}\b')
_MATRICULA = re.compile(
    r'\b(?:mat(?:r[íi]cula)?\.?\s*:?\s*)[\d\w\-\.\/]{4,20}\b'
    r'|\b\d{1,3}(?:\.\d{3})+[\-\/]\d{1,2}\b',
    re.IGNORECASE
)
_NOME_COMPOSTO = re.compile(
    r'\b[A-ZÁÉÍÓÚÂÊÔÃÕÀÜÇ][a-záéíóúâêôãõàüç]+'
    r'(?:\s+(?:da?|de|do|dos|das|e))*'
    r'(?:\s+[A-Za-záéíóúâêôãõàüçÁÉÍÓÚÂÊÔÃÕÀÜÇ][a-záéíóúâêôãõàüç]+){1,4}\b'
)
_NOME_POS_PONTUACAO = re.compile(
    r'(?<=[\.!\?])\s*([A-ZÁÉÍÓÚÂÊÔÃÕÀÜÇ][a-záéíóúâêôãõàüç]{2,})\b'
)
_CAIXA_ALTA_CONTEXTO = re.compile(
    r'\b(SRA?\.?|SRTA\.?|SGT\.?|SENHORA|SENHOR|AGENTE|VITIMA|VÍTIMA|'
    r'SOLICITANTE|AUTOR[A]?|SUSPEITO[A]?|COMPANHEIRO|COMPANHEIRA|'
    r'NAMORADO[A]?|IRM[AÃ]O?|FILHO[A]?|PADRASTO|MAE|MÃE|PAI|AVÔ|AVO|'
    r'ESPOSA|ESPOSO|MARIDO|SOGR[AO]|GENRO|CUNHAD[AO]|CONCUNHAD[AO]|'
    r'MAE\s+D[AO]|PAI\s+D[AO]|'
    r'PELO\s+AGENTE|PELA\s+AGENTE|'
    r'POSTERIORMENTE\s+IDENTIFICAD[OA]\s+COMO(?:\s+SENDO)?|'
    r'IDENTIFICAD[OA]\s+COMO(?:\s+SENDO)?)'
    r'[\s,\(]+'
    r'([A-ZÁÉÍÓÚÂÊÔÃÕÀÜÇ][A-ZÁÉÍÓÚÂÊÔÃÕÀÜÇa-záéíóúâêôãõàüç]+'
    r'(?:\s+(?:DA?|DE|DO|DOS|DAS)\s+[A-ZÁÉÍÓÚÂÊÔÃÕÀÜÇ][A-ZÁÉÍÓÚÂÊÔÃÕÀÜÇ]+|'
    r'\s+[A-ZÁÉÍÓÚÂÊÔÃÕÀÜÇ][A-ZÁÉÍÓÚÂÊÔÃÕÀÜÇ]+)*)'
)


def _substituir_nomes_caixa_alta(texto):
    def _sub(match):
        palavra = match.group(2)
        if palavra.upper() in PALAVRAS_COMUNS:
            return match.group(0)
        return match.group(1) + ' [NOME]'
    return _CAIXA_ALTA_CONTEXTO.sub(_sub, texto)


def _texto_e_caixa_alta(texto):
    letras = [c for c in texto if c.isalpha()]
    if not letras:
        return False
    return sum(1 for c in letras if c.isupper()) / len(letras) > 0.70


def anonimizar_coluna(df, coluna="HISTORICO"):

    def proteger_whitelist(texto):
        protegidos = {}
        for regex, placeholder in _WHITELIST_COMPILED:
            encontrado = regex.search(texto)
            if encontrado:
                protegidos[placeholder] = encontrado.group(0)
                texto = regex.sub(placeholder, texto)
        return texto, protegidos

    def restaurar_whitelist(texto, protegidos):
        for placeholder, original in protegidos.items():
            texto = texto.replace(placeholder, original)
        return texto

    def anonimizar_texto(texto):
        if not isinstance(texto, str):
            return texto

        caixa_alta = _texto_e_caixa_alta(texto)
        texto, protegidos = proteger_whitelist(texto)

        texto = _CPF.sub('[CPF]', texto)
        texto = _CNPJ.sub('[CNPJ]', texto)
        texto = _MATRICULA.sub('[CODIGO]', texto)
        texto = _EMAIL.sub('[EMAIL]', texto)
        texto = _TELEFONE.sub('[TELEFONE]', texto)
        texto = _CODIGO.sub('[CODIGO]', texto)

        # Lista de nomes e sobrenomes conhecidos
        for regex_nome in _NOMES_COMPILED:
            texto = regex_nome.sub('[NOME]', texto)

        if caixa_alta:
            texto = _substituir_nomes_caixa_alta(texto)
        else:
            texto = _NOME_COMPOSTO.sub('[NOME]', texto)
            texto = CONTEXTO.sub(lambda m: f"{m.group(1)} [NOME]", texto)
            texto = _NOME_POS_PONTUACAO.sub('[NOME]', texto)

        texto = restaurar_whitelist(texto, protegidos)
        return texto

    df[coluna] = df[coluna].apply(anonimizar_texto)
    return df